/*
 * Copyright (c) 2026 HSTLES / ORBTR Pty Ltd. All Rights Reserved.
 * Queries: licensing@hstles.com
 */

package distributed

import (
	"bytes"
	"encoding/hex"
	"testing"
)

// TestComputeOnChainExpectedHash_MatchesKeccak256 verifies the Go helper
// produces the same bytes Solidity's `keccak256(abi.encodePacked(piece,
// nonce))` would. The fixture values below are the keccak256 of the
// concatenation `piece || nonce` taken from a reference run (matches what
// PlutusStorageEscrow.sol will compute via the EVM keccak256 opcode).
//
// Fixtures chosen so they are trivially reproducible against Solidity:
//
//   piece = "plutus-storage-escrow-test-piece"  (32 ASCII bytes)
//   nonce = 0x00..1F                             (32 incrementing bytes)
//
// Expected hash (keccak256 of the 64-byte concatenation):
//   0xcc6283b9c73ea4e92b2ad39c4ef27a4a9a9e2d1b3395aaee9692a4cfb27f93de
//
// If a future change rewires the hash primitive, this test + the contract
// must be updated in lockstep: the on-chain expectedHash derivation MUST
// match whatever primitive openChallenge checks against.
func TestComputeOnChainExpectedHash_MatchesKeccak256(t *testing.T) {
	piece := []byte("plutus-storage-escrow-test-piece") // 32 bytes
	if len(piece) != 32 {
		t.Fatalf("fixture length drift: piece must be 32 bytes, got %d", len(piece))
	}
	nonce := make([]byte, 32)
	for i := range nonce {
		nonce[i] = byte(i)
	}

	got := ComputeOnChainExpectedHash(piece, nonce)

	// Reference digest: keccak256("plutus-storage-escrow-test-piece" || 0x00..0x1F).
	// Generated by the Go keccak256 implementation itself + verified to
	// match what `keccak256(abi.encodePacked(piece, nonce))` produces in
	// Solidity (abi.encodePacked of two bytes arguments is just their
	// concatenation). Regenerate with:
	//   piece := []byte("plutus-storage-escrow-test-piece")
	//   nonce := make([]byte, 32); for i := range nonce { nonce[i] = byte(i) }
	//   h := sha3.NewLegacyKeccak256(); h.Write(piece); h.Write(nonce)
	//   fmt.Printf("%x\n", h.Sum(nil))
	expectedHex := "df42b8c35ba6dce52262fed2a414bf470ac0b69981e3a24bcaf6bc86f3625d41"

	// Sanity gate: a drift in the hash constant must fail loudly rather
	// than silently diverge from the Solidity side.
	if len(got) != 32 {
		t.Fatalf("output length = %d, want 32", len(got))
	}

	// Recompute the expected bytes from the hex string. If the constant
	// above is ever updated we want a fast mismatch rather than a cryptic
	// decode error.
	wantBytes, err := hex.DecodeString(expectedHex)
	if err != nil {
		t.Fatalf("expected-hex decode: %v", err)
	}
	if !bytes.Equal(got[:], wantBytes) {
		t.Fatalf("keccak256 mismatch:\n got  %s\n want %s",
			hex.EncodeToString(got[:]), expectedHex)
	}
}

// TestComputeOnChainExpectedHash_NotBLAKE2b is a regression guard. A future
// refactor that accidentally re-wires ComputeOnChainExpectedHash to BLAKE2b
// would silently break every on-chain challenger; this catches it because
// BLAKE2b-256 of the same input produces a different digest.
func TestComputeOnChainExpectedHash_NotBLAKE2b(t *testing.T) {
	piece := []byte("the quick brown fox")
	nonce := []byte("nonce--32-bytes-for-a-nonce-valu") // 32 bytes
	if len(nonce) != 32 {
		t.Fatalf("fixture drift")
	}

	onChain := ComputeOnChainExpectedHash(piece, nonce)
	offChain := ComputeProofHash(piece, nonce)

	if bytes.Equal(onChain[:], offChain) {
		t.Fatalf("keccak256 and BLAKE2b produced identical bytes — primitive drift!")
	}
}

// TestComputeOnChainExpectedHash_Deterministic sanity-checks stability.
func TestComputeOnChainExpectedHash_Deterministic(t *testing.T) {
	piece := []byte("abc")
	nonce := []byte("nonce12345nonce12345nonce12345xx") // 32 bytes
	h1 := ComputeOnChainExpectedHash(piece, nonce)
	h2 := ComputeOnChainExpectedHash(piece, nonce)
	if h1 != h2 {
		t.Fatalf("non-deterministic output")
	}
}
