// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pb/record.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LADRecord is the wire format for directory records in gossip exchanges.
// Each consumer defines its own record structure. HSTLES/ORBTR uses this
// for member, role, reach, and latency records. Hospitium defines CRDT
// record protos separately.
type LADRecord struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Topic           string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NodeId          string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Body            []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	TimestampUnix   int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	LamportClock    uint64                 `protobuf:"varint,6,opt,name=lamport_clock,json=lamportClock,proto3" json:"lamport_clock,omitempty"`
	Seq             uint64                 `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	Tombstone       bool                   `protobuf:"varint,8,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	DeletedAtUnix   int64                  `protobuf:"varint,9,opt,name=deleted_at_unix,json=deletedAtUnix,proto3" json:"deleted_at_unix,omitempty"`
	TombstoneReason string                 `protobuf:"bytes,10,opt,name=tombstone_reason,json=tombstoneReason,proto3" json:"tombstone_reason,omitempty"`
	Signature       []byte                 `protobuf:"bytes,11,opt,name=signature,proto3" json:"signature,omitempty"`
	HlcTimestamp    uint64                 `protobuf:"varint,12,opt,name=hlc_timestamp,json=hlcTimestamp,proto3" json:"hlc_timestamp,omitempty"`
	AuthorPubkey    []byte                 `protobuf:"bytes,13,opt,name=author_pubkey,json=authorPubkey,proto3" json:"author_pubkey,omitempty"`
	BlobCid         string                 `protobuf:"bytes,14,opt,name=blob_cid,json=blobCid,proto3" json:"blob_cid,omitempty"`
	ExpiresAtUnix   int64                  `protobuf:"varint,15,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LADRecord) Reset() {
	*x = LADRecord{}
	mi := &file_pb_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LADRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LADRecord) ProtoMessage() {}

func (x *LADRecord) ProtoReflect() protoreflect.Message {
	mi := &file_pb_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LADRecord.ProtoReflect.Descriptor instead.
func (*LADRecord) Descriptor() ([]byte, []int) {
	return file_pb_record_proto_rawDescGZIP(), []int{0}
}

func (x *LADRecord) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *LADRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LADRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LADRecord) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *LADRecord) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *LADRecord) GetLamportClock() uint64 {
	if x != nil {
		return x.LamportClock
	}
	return 0
}

func (x *LADRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *LADRecord) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *LADRecord) GetDeletedAtUnix() int64 {
	if x != nil {
		return x.DeletedAtUnix
	}
	return 0
}

func (x *LADRecord) GetTombstoneReason() string {
	if x != nil {
		return x.TombstoneReason
	}
	return ""
}

func (x *LADRecord) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *LADRecord) GetHlcTimestamp() uint64 {
	if x != nil {
		return x.HlcTimestamp
	}
	return 0
}

func (x *LADRecord) GetAuthorPubkey() []byte {
	if x != nil {
		return x.AuthorPubkey
	}
	return nil
}

func (x *LADRecord) GetBlobCid() string {
	if x != nil {
		return x.BlobCid
	}
	return ""
}

func (x *LADRecord) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

var File_pb_record_proto protoreflect.FileDescriptor

const file_pb_record_proto_rawDesc = "" +
	"\n" +
	"\x0fpb/record.proto\x12\tledger.v1\"\xe5\x03\n" +
	"\tLADRecord\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\x12#\n" +
	"\rlamport_clock\x18\x06 \x01(\x04R\flamportClock\x12\x10\n" +
	"\x03seq\x18\a \x01(\x04R\x03seq\x12\x1c\n" +
	"\ttombstone\x18\b \x01(\bR\ttombstone\x12&\n" +
	"\x0fdeleted_at_unix\x18\t \x01(\x03R\rdeletedAtUnix\x12)\n" +
	"\x10tombstone_reason\x18\n" +
	" \x01(\tR\x0ftombstoneReason\x12\x1c\n" +
	"\tsignature\x18\v \x01(\fR\tsignature\x12#\n" +
	"\rhlc_timestamp\x18\f \x01(\x04R\fhlcTimestamp\x12#\n" +
	"\rauthor_pubkey\x18\r \x01(\fR\fauthorPubkey\x12\x19\n" +
	"\bblob_cid\x18\x0e \x01(\tR\ablobCid\x12&\n" +
	"\x0fexpires_at_unix\x18\x0f \x01(\x03R\rexpiresAtUnixB Z\x1egithub.com/bbmumford/ledger/pbb\x06proto3"

var (
	file_pb_record_proto_rawDescOnce sync.Once
	file_pb_record_proto_rawDescData []byte
)

func file_pb_record_proto_rawDescGZIP() []byte {
	file_pb_record_proto_rawDescOnce.Do(func() {
		file_pb_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_record_proto_rawDesc), len(file_pb_record_proto_rawDesc)))
	})
	return file_pb_record_proto_rawDescData
}

var file_pb_record_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_record_proto_goTypes = []any{
	(*LADRecord)(nil), // 0: ledger.v1.LADRecord
}
var file_pb_record_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_record_proto_init() }
func file_pb_record_proto_init() {
	if File_pb_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_record_proto_rawDesc), len(file_pb_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_record_proto_goTypes,
		DependencyIndexes: file_pb_record_proto_depIdxs,
		MessageInfos:      file_pb_record_proto_msgTypes,
	}.Build()
	File_pb_record_proto = out.File
	file_pb_record_proto_goTypes = nil
	file_pb_record_proto_depIdxs = nil
}
